import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import 'dotenv/config';
import path from 'path';
import { errors } from 'celebrate';
import productRouter from './routes/product';
import orderRouter from './routes/order';
import errorHandler from './middlewares/error-handler';
import { errorLogger, requestLogger } from './middlewares/logger';

const { DB_ADDRESS = 'mongodb://127.0.0.1:27017/web-larek' } = process.env;
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
mongoose.connect(DB_ADDRESS);
app.use(express.static(path.join(__dirname, '../public')));
app.use(cors());
app.use(requestLogger);
app.use('/product', productRouter);
app.use('/order', orderRouter);
app.use(errorLogger);
app.use(errors());
app.use(errorHandler);
app.listen(3000);
